name: LaTeX to PDF

on:
  push:
    paths:
      - "thesis/**"
      - "abst/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build docker image
        uses: k-kana/latex-build-using-github-actions/.github/actions/latex@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
